# Generated by Django 5.2.5 on 2025-09-02 16:13

import django.db.models.deletion
import libarayapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libarayapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='products/images/', validators=[libarayapp.validators.validate_file_size])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='libarayapp.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
