# Generated by Django 5.2.5 on 2025-09-03 05:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libarayapp', '0002_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
